### ISSUE TITLE
tiny_imagenet run results only 1.%

### ISSUE THREAD

**Issue by snownus** [gushan/SGDAT#1]
@gushan1987

Dear Authors, 

I have tried to run the tiny-imagenet using SGDAT and ADAM, I found that for the code, training precision is normal. However, the validation accurary is around 1.%. Could you please help to fix it?

**Comment by snownus** [comment]
The problem is addressed as I need to use the preprocess script in datasets/ folder to preprocess the downloaded tiny imagenet dataset.

**Comment by gushan1987** [comment]
Got it, thanks for letting me know. If you have any further concerns or questions, please contact me.
